on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/6945c5d9a3fb90d4bb9c82a18d7f70fd
          gist_title: 20-MPLAB-BluetoothHC05-4550.c
          gist_description: Prácticas MPLABX
          github_file: Proyecto/PIC18F4550/20_HC05.X/main.c
          file_encoding: ISO-8859-1
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/76f991b02f89535b3a7db88806ba33f3
          gist_title: 20-MPLAB-BluetoothHC05.c
          gist_description: Prácticas MPLABX
          github_file: Proyecto/PIC18F45K50/20_BT_HC05.X/main.c
          file_encoding: ISO-8859-1